### ISSUE TITLE
Bug in chapter 9, line 380

### ISSUE THREAD

**Issue by denniskb** [asweigart/inventwithpython3rded#69]
> 378&nbsp;&nbsp;&nbsp;&nbsp;Try entering 'Hello world!'.lower() into the interactive shell to see an example of this method:
> 379
> 380&nbsp;&nbsp;&nbsp;&nbsp;\>\>\> 'Hello world'.lower()
> 381&nbsp;&nbsp;&nbsp;&nbsp;'hello world!'

should be:

378&nbsp;&nbsp;&nbsp;&nbsp;Try entering 'Hello world!'.lower() into the interactive shell to see an example of this method:
379
380&nbsp;&nbsp;&nbsp;&nbsp;\>\>\> 'Hello world**!**'.lower()
381&nbsp;&nbsp;&nbsp;&nbsp;'hello world!'

**Comment by asweigart** [comment]
Thanks! Fixed and closed.
