### ISSUE TITLE
Inconsistent use of exclamation marks in chapter 9, lines 383-417

### ISSUE THREAD

**Issue by denniskb** [asweigart/inventwithpython3rded#70]
Lines 383-417 in chapter 9 explain the methods lower() and upper(). They use the string 'Hellow world!' to illustrate the effect of both methods. However, sometimes the text says 'Hello world!', sometimes it says 'Hello world'; the same is true for the corresponding code samples.

**Comment by asweigart** [comment]
Fixed. Thanks for the report!
