### ISSUE TITLE
Missing newline(s) in chapter 9?

### ISSUE THREAD

**Issue by denniskb** [asweigart/inventwithpython3rded#71]
> &nbsp;&nbsp;&nbsp;&nbsp;522&nbsp;&nbsp;&nbsp;&nbsp;['H', 'e', 'l', 'l', 'o']
> \>
> &nbsp;&nbsp;&nbsp;&nbsp;523&nbsp;&nbsp;&nbsp;&nbsp;The list() function is similar to the str() or int() functions. It just converts the object it is passed into a list. It’s easy to generate huge lists with the range() function. Try entering in list(range(10000)) into the interactive shell:
> \>
> &nbsp;&nbsp;&nbsp;&nbsp;524&nbsp;&nbsp;&nbsp;&nbsp;\>\>\> list(range(10000))

**Comment by asweigart** [comment]
Fixed. Thanks Dennis!
