### ISSUE TITLE
Bug in chapter 9, lines 740-745

### ISSUE THREAD

**Issue by denniskb** [asweigart/inventwithpython3rded#74]
Missing colon after elif:

>if catName == 'Fuzzball':
>&nbsp;&nbsp;&nbsp;&nbsp;print('Your cat is fuzzy.')
>elif catName == 'Spots'**:**
>&nbsp;&nbsp;&nbsp;&nbsp;print('Your cat is spotted.')
>else:
>&nbsp;&nbsp;&nbsp;&nbsp;print('Your cat is not fuzzy or spotted.')

**Comment by asweigart** [comment]
Fixed. Thanks Dennis!
