### ISSUE TITLE
Bug in chapter 9, lines 751-760

### ISSUE THREAD

**Issue by denniskb** [asweigart/inventwithpython3rded#75]
Missing colons after elifs:

>if catName == 'Fuzzball':
>&nbsp;&nbsp;&nbsp;&nbsp;print('Your cat is fuzzy.')
>elif catName == 'Spots'**:**
>&nbsp;&nbsp;&nbsp;&nbsp;print('Your cat is spotted.')
>elif catName == 'Chubs'**:**
>&nbsp;&nbsp;&nbsp;&nbsp;print('Your cat is chubby.')
>elif catName == 'Puff'**:**
>&nbsp;&nbsp;&nbsp;&nbsp;print('Your cat is puffy.')
>else:
>&nbsp;&nbsp;&nbsp;&nbsp;print('Your cat is neither fuzzy nor spotted nor chubby nor puffy.')

**Comment by denniskb** [comment]
Were you drunk when you wrote chapter 9? xD

**Comment by asweigart** [comment]
Fixed. Thanks!

And I'm ALWAYS drunk when I write. :)
